[2024-02-10 11:00:54,044] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.add_files scheduled__2024-02-10T10:52:00+00:00 [queued]>
[2024-02-10 11:00:54,179] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.add_files scheduled__2024-02-10T10:52:00+00:00 [queued]>
[2024-02-10 11:00:54,183] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 11:00:54,185] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-10 11:00:54,189] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 11:00:54,372] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): add_files> on 2024-02-10 10:52:00+00:00
[2024-02-10 11:00:54,474] {standard_task_runner.py:52} INFO - Started process 105 to run task
[2024-02-10 11:00:54,652] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_dependencies', 'add_files', 'scheduled__2024-02-10T10:52:00+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_dependencies.py', '--cfg-path', '/tmp/tmpwed_7dtp', '--error-file', '/tmp/tmp2095n3e_']
[2024-02-10 11:00:54,776] {standard_task_runner.py:80} INFO - Job 172: Subtask add_files
[2024-02-10 11:00:55,760] {task_command.py:369} INFO - Running <TaskInstance: test_dag_dependencies.add_files scheduled__2024-02-10T10:52:00+00:00 [running]> on host f4c5b03650dc
[2024-02-10 11:00:56,135] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=fidiasierides@gmail.com
AIRFLOW_CTX_DAG_OWNER=Fidias
AIRFLOW_CTX_DAG_ID=test_dag_dependencies
AIRFLOW_CTX_TASK_ID=add_files
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T10:52:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T10:52:00+00:00
[2024-02-10 11:00:56,140] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-10 11:00:56,144] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'WORKDIR "/Documents/GitHub/weather-data-store" && git add .']
[2024-02-10 11:00:56,230] {subprocess.py:85} INFO - Output:
[2024-02-10 11:00:56,232] {subprocess.py:92} INFO - bash: line 1: WORKDIR: command not found
[2024-02-10 11:00:56,234] {subprocess.py:96} INFO - Command exited with return code 127
[2024-02-10 11:00:56,306] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-02-10 11:00:56,329] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test_dag_dependencies, task_id=add_files, execution_date=20240210T105200, start_date=20240210T110054, end_date=20240210T110056
[2024-02-10 11:00:56,473] {standard_task_runner.py:97} ERROR - Failed to execute job 172 for task add_files (Bash command failed. The command returned a non-zero exit code 127.; 105)
[2024-02-10 11:00:56,564] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-10 11:00:56,777] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
