[2024-02-10 19:23:00,670] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag.write_date_file scheduled__2024-02-10T19:22:00+00:00 [queued]>
[2024-02-10 19:23:00,676] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag.write_date_file scheduled__2024-02-10T19:22:00+00:00 [queued]>
[2024-02-10 19:23:00,676] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 19:23:00,676] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-10 19:23:00,677] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 19:23:00,684] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): write_date_file> on 2024-02-10 19:22:00+00:00
[2024-02-10 19:23:00,687] {standard_task_runner.py:52} INFO - Started process 820 to run task
[2024-02-10 19:23:00,689] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'write_date_file', 'scheduled__2024-02-10T19:22:00+00:00', '--job-id', '516', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_dependencies.py', '--cfg-path', '/tmp/tmpr6wyeiqu', '--error-file', '/tmp/tmpdlj15em2']
[2024-02-10 19:23:00,689] {standard_task_runner.py:80} INFO - Job 516: Subtask write_date_file
[2024-02-10 19:23:00,716] {task_command.py:369} INFO - Running <TaskInstance: test_dag.write_date_file scheduled__2024-02-10T19:22:00+00:00 [running]> on host f4c5b03650dc
[2024-02-10 19:23:00,760] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=fidiasierides@gmail.com
AIRFLOW_CTX_DAG_OWNER=Fidias
AIRFLOW_CTX_DAG_ID=test_dag
AIRFLOW_CTX_TASK_ID=write_date_file
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T19:22:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T19:22:00+00:00
[2024-02-10 19:23:00,761] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-10 19:23:00,761] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd ~/Desktop && date >> ai_core.txt']
[2024-02-10 19:23:00,768] {subprocess.py:85} INFO - Output:
[2024-02-10 19:23:00,770] {subprocess.py:92} INFO - bash: line 1: cd: /home/***/Desktop: No such file or directory
[2024-02-10 19:23:00,770] {subprocess.py:96} INFO - Command exited with return code 1
[2024-02-10 19:23:00,779] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-10 19:23:00,781] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test_dag, task_id=write_date_file, execution_date=20240210T192200, start_date=20240210T192300, end_date=20240210T192300
[2024-02-10 19:23:00,788] {standard_task_runner.py:97} ERROR - Failed to execute job 516 for task write_date_file (Bash command failed. The command returned a non-zero exit code 1.; 820)
[2024-02-10 19:23:00,828] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-10 19:23:00,846] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
