[2024-02-10 08:12:24,297] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T08:06:00+00:00 [queued]>
[2024-02-10 08:12:24,308] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T08:06:00+00:00 [queued]>
[2024-02-10 08:12:24,309] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 08:12:24,309] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2024-02-10 08:12:24,309] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 08:12:24,329] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): write_date> on 2024-02-10 08:06:00+00:00
[2024-02-10 08:12:24,336] {standard_task_runner.py:52} INFO - Started process 34555 to run task
[2024-02-10 08:12:24,358] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_dependencies', 'write_date', 'scheduled__2024-02-10T08:06:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_dependencies.py', '--cfg-path', '/tmp/tmp6c8c4fwl', '--error-file', '/tmp/tmp2qw2bg8q']
[2024-02-10 08:12:24,360] {standard_task_runner.py:80} INFO - Job 67: Subtask write_date
[2024-02-10 08:12:24,512] {task_command.py:369} INFO - Running <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T08:06:00+00:00 [running]> on host f4c5b03650dc
[2024-02-10 08:12:24,581] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=fidiasierides@gmail.com
AIRFLOW_CTX_DAG_OWNER=Fidias
AIRFLOW_CTX_DAG_ID=test_dag_dependencies
AIRFLOW_CTX_TASK_ID=write_date
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T08:06:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T08:06:00+00:00
[2024-02-10 08:12:24,582] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-10 08:12:24,583] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'WORKDIR "/Documents/GitHub/weather-data-store" && date >> date.txt']
[2024-02-10 08:12:24,592] {subprocess.py:85} INFO - Output:
[2024-02-10 08:12:24,603] {subprocess.py:92} INFO - bash: line 1: WORKDIR: command not found
[2024-02-10 08:12:24,604] {subprocess.py:96} INFO - Command exited with return code 127
[2024-02-10 08:12:24,615] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-02-10 08:12:24,619] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test_dag_dependencies, task_id=write_date, execution_date=20240210T080600, start_date=20240210T081224, end_date=20240210T081224
[2024-02-10 08:12:24,627] {standard_task_runner.py:97} ERROR - Failed to execute job 67 for task write_date (Bash command failed. The command returned a non-zero exit code 127.; 34555)
[2024-02-10 08:12:24,663] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-10 08:12:24,690] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
