[2024-02-10 18:59:01,234] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T18:58:00+00:00 [queued]>
[2024-02-10 18:59:01,241] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T18:58:00+00:00 [queued]>
[2024-02-10 18:59:01,241] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 18:59:01,241] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-10 18:59:01,241] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 18:59:01,255] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): write_date> on 2024-02-10 18:58:00+00:00
[2024-02-10 18:59:01,266] {standard_task_runner.py:52} INFO - Started process 4799 to run task
[2024-02-10 18:59:01,271] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_dependencies', 'write_date', 'scheduled__2024-02-10T18:58:00+00:00', '--job-id', '467', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_dependencies.py', '--cfg-path', '/tmp/tmpnsxqfra7', '--error-file', '/tmp/tmpk37pkh6x']
[2024-02-10 18:59:01,271] {standard_task_runner.py:80} INFO - Job 467: Subtask write_date
[2024-02-10 18:59:01,312] {task_command.py:369} INFO - Running <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T18:58:00+00:00 [running]> on host f4c5b03650dc
[2024-02-10 18:59:01,373] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=fidiasierides@gmail.com
AIRFLOW_CTX_DAG_OWNER=Fidias
AIRFLOW_CTX_DAG_ID=test_dag_dependencies
AIRFLOW_CTX_TASK_ID=write_date
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T18:58:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T18:58:00+00:00
[2024-02-10 18:59:01,375] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-10 18:59:01,375] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd ~/Desktop && date >> date.txt']
[2024-02-10 18:59:01,383] {subprocess.py:85} INFO - Output:
[2024-02-10 18:59:01,385] {subprocess.py:92} INFO - bash: line 1: cd: /home/***/Desktop: No such file or directory
[2024-02-10 18:59:01,385] {subprocess.py:96} INFO - Command exited with return code 1
[2024-02-10 18:59:01,393] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-10 18:59:01,395] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test_dag_dependencies, task_id=write_date, execution_date=20240210T185800, start_date=20240210T185901, end_date=20240210T185901
[2024-02-10 18:59:01,404] {standard_task_runner.py:97} ERROR - Failed to execute job 467 for task write_date (Bash command failed. The command returned a non-zero exit code 1.; 4799)
[2024-02-10 18:59:01,411] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-10 18:59:01,434] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
