[2024-02-10 18:06:01,382] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T18:05:00+00:00 [queued]>
[2024-02-10 18:06:01,401] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T18:05:00+00:00 [queued]>
[2024-02-10 18:06:01,402] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 18:06:01,405] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-10 18:06:01,424] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-10 18:06:01,504] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): write_date> on 2024-02-10 18:05:00+00:00
[2024-02-10 18:06:01,537] {standard_task_runner.py:52} INFO - Started process 3231 to run task
[2024-02-10 18:06:01,547] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test_dag_dependencies', 'write_date', 'scheduled__2024-02-10T18:05:00+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/dag_test_dependencies.py', '--cfg-path', '/tmp/tmpez7_0kd0', '--error-file', '/tmp/tmp12izq1vj']
[2024-02-10 18:06:01,548] {standard_task_runner.py:80} INFO - Job 401: Subtask write_date
[2024-02-10 18:06:01,609] {task_command.py:369} INFO - Running <TaskInstance: test_dag_dependencies.write_date scheduled__2024-02-10T18:05:00+00:00 [running]> on host f4c5b03650dc
[2024-02-10 18:06:01,670] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=fidiasierides@gmail.com
AIRFLOW_CTX_DAG_OWNER=Fidias
AIRFLOW_CTX_DAG_ID=test_dag_dependencies
AIRFLOW_CTX_TASK_ID=write_date
AIRFLOW_CTX_EXECUTION_DATE=2024-02-10T18:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-10T18:05:00+00:00
[2024-02-10 18:06:01,671] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-02-10 18:06:01,671] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd ~/Users/fidiasieridis/Desktop/Weather_Airflow && date >> date.txt']
[2024-02-10 18:06:01,680] {subprocess.py:85} INFO - Output:
[2024-02-10 18:06:01,682] {subprocess.py:92} INFO - bash: line 1: cd: /home/***/Users/fidiasieridis/Desktop/Weather_Airflow: No such file or directory
[2024-02-10 18:06:01,683] {subprocess.py:96} INFO - Command exited with return code 1
[2024-02-10 18:06:01,693] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-02-10 18:06:01,695] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test_dag_dependencies, task_id=write_date, execution_date=20240210T180500, start_date=20240210T180601, end_date=20240210T180601
[2024-02-10 18:06:01,703] {standard_task_runner.py:97} ERROR - Failed to execute job 401 for task write_date (Bash command failed. The command returned a non-zero exit code 1.; 3231)
[2024-02-10 18:06:01,728] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-02-10 18:06:01,754] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
